# Generated by Django 6.1 on 2026-08-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(help_text='app_label.ModelName', max_length=100)),
                ('table', models.JSONField(blank=True, default=dict)),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('infolist', models.JSONField(blank=True, default=dict)),
                ('nav_group', models.CharField(blank=True, max_length=60)),
                ('nav_icon', models.CharField(blank=True, max_length=60)),
                ('permission_prefix', models.CharField(blank=True, max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'dashboard spec',
            },
        ),
    ]
