# Generated by Django 6.1 on 2026-08-29 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dcc_studio', '0002_paneldashboard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardspec',
            options={'permissions': (('use_studio', 'Can use the studio builder'),), 'verbose_name': 'dashboard spec'},
        ),
        migrations.AddField(
            model_name='dashboardspec',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='+', to='auth.group', verbose_name='visible to groups'),
        ),
        migrations.AddField(
            model_name='dashboardspec',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Visible to every authenticated user.'),
        ),
        migrations.AddField(
            model_name='dashboardspec',
            name='required_permission',
            field=models.CharField(blank=True, help_text='e.g. "blog.view_article"', max_length=100),
        ),
        migrations.AddField(
            model_name='dashboardspec',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardspec',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='visible to users'),
        ),
        migrations.AddField(
            model_name='paneldashboard',
            name='default_for_groups',
            field=models.ManyToManyField(blank=True, related_name='+', to='auth.group', verbose_name='default home for groups'),
        ),
        migrations.AddField(
            model_name='paneldashboard',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='+', to='auth.group', verbose_name='visible to groups'),
        ),
        migrations.AddField(
            model_name='paneldashboard',
            name='is_default',
            field=models.BooleanField(default=False, help_text='A fallback home dashboard when a user has no other.'),
        ),
        migrations.AddField(
            model_name='paneldashboard',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Visible to every authenticated user.'),
        ),
        migrations.AddField(
            model_name='paneldashboard',
            name='required_permission',
            field=models.CharField(blank=True, help_text='e.g. "blog.view_article"', max_length=100),
        ),
        migrations.AddField(
            model_name='paneldashboard',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paneldashboard',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='visible to users'),
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False, help_text='Visible to every authenticated user.')),
                ('required_permission', models.CharField(blank=True, help_text='e.g. "blog.view_article"', max_length=100)),
                ('panel', models.CharField(db_index=True, help_text='Panel.name', max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=60)),
                ('order', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('target_kind', models.CharField(choices=[('group', 'Group heading'), ('resource', 'Code resource'), ('spec', 'Studio resource'), ('dashboard', 'Studio dashboard'), ('url_name', 'Named URL'), ('url', 'URL / path')], default='url', max_length=20)),
                ('target', models.CharField(blank=True, max_length=300)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='+', to='auth.group', verbose_name='visible to groups')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dcc_studio.navitem')),
                ('users', models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='visible to users')),
            ],
            options={
                'verbose_name': 'navigation item',
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SpecRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dashboard_spec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='dcc_studio.dashboardspec')),
                ('panel_dashboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='dcc_studio.paneldashboard')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_kind', models.CharField(blank=True, max_length=20)),
                ('home_target', models.CharField(blank=True, max_length=300)),
                ('sidebar_collapsed', models.BooleanField(default=False)),
                ('theme', models.CharField(choices=[('auto', 'Auto'), ('light', 'Light'), ('dark', 'Dark')], default='auto', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dcc_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
