# Generated by Django 6.1 on 2026-08-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcc_studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('widgets', models.JSONField(blank=True, default=list)),
                ('nav_group', models.CharField(blank=True, max_length=60)),
                ('nav_icon', models.CharField(blank=True, max_length=60)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'panel dashboard',
            },
        ),
    ]
