# Generated by Django 6.1 on 2026-09-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcc_studio', '0003_studio'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel', models.CharField(help_text='Panel.name', max_length=100, unique=True)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'navigation document',
            },
        ),
    ]
