# Generated by Django 6.1 on 2026-09-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcc_studio', '0004_navdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioEntry',
            fields=[
            ],
            options={
                'verbose_name': 'studio',
                'verbose_name_plural': 'studio',
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('dcc_studio.dashboardspec',),
        ),
    ]
