# Generated by Django 6.1 on 2026-09-01 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dcc_studio', '0006_remove_dashboardspec_is_public_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('public', 'Everyone, including signed-out visitors'), ('auth', 'Any signed-in user'), ('restricted', 'Only the groups / users / permission below')], default='restricted', max_length=10)),
                ('required_permission', models.CharField(blank=True, help_text='e.g. "blog.view_article"', max_length=100)),
                ('mount', models.CharField(choices=[('panel', 'In-app, inside a panel'), ('site', 'Public site')], default='panel', max_length=10)),
                ('panel', models.CharField(blank=True, help_text='Panel.name when mount=panel', max_length=100)),
                ('route', models.CharField(blank=True, help_text='"" for the index page', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('tree', models.JSONField(blank=True, default=dict)),
                ('schema_version', models.PositiveIntegerField(default=0)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_home', models.BooleanField(default=False)),
                ('show_in_nav', models.BooleanField(default=True)),
                ('nav_label', models.CharField(blank=True, max_length=100)),
                ('nav_icon', models.CharField(blank=True, max_length=60)),
                ('nav_group', models.CharField(blank=True, max_length=60)),
                ('nav_order', models.IntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='+', to='auth.group', verbose_name='visible to groups')),
                ('users', models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='visible to users')),
            ],
            options={
                'verbose_name': 'page',
                'ordering': ('mount', 'panel', 'nav_order', 'route'),
                'unique_together': {('mount', 'panel', 'route')},
            },
        ),
        migrations.AddField(
            model_name='specrevision',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='dcc_studio.page'),
        ),
    ]
