# Generated by Django 6.1 on 2026-09-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcc_studio', '0007_page_specrevision_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navitem',
            name='target_kind',
            field=models.CharField(choices=[('group', 'Group heading'), ('resource', 'Code resource'), ('spec', 'Studio resource'), ('dashboard', 'Studio dashboard'), ('page', 'Studio page'), ('url_name', 'Named URL'), ('url', 'URL / path')], default='url', max_length=20),
        ),
    ]
